@startuml person
!define LIGHTBLUE
!includeurl https://gist.githubusercontent.com/amgs/de57560012a8a5f0e4240f392b678a40/raw/c903c6b4f16b60b5eef3248f093497faae378f51/style.puml
class Person {
    #Person(String id, String name, int age)
    +String getId()
    +String getName()
    +int getAge()
}
@enduml